version: 2

defaults: &defaults
  docker:
    - image: debian:stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: run build
          command: |
            echo "build"
  another_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: run another
          command: |
            echo "another"

workflows:
  version: 2
  playground:
    jobs:
      - build
      - another_job:
          requires:
            - build
